# Generated by Django 5.1.3 on 2024-11-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_banqueteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_evento',
            field=models.DateTimeField(),
        ),
    ]
